### ISSUE TITLE
it is not working for me dear.

### ISSUE THREAD

**Issue by Bisratshewaye** [dawnlinch/AceFileClone#1]
**Warning: require_once(C:\xampp\htdocs/library/autoload.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\AceFileClone-main\template\header.php on line 1**

Fatal error: Uncaught Error: Failed opening required 'C:\xampp\htdocs/library/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\AceFileClone-main\template\header.php:1 Stack trace: #0 C:\xampp\htdocs\AceFileClone-main\index.php(1): include() #1 {main} thrown in C:\xampp\htdocs\AceFileClone-main\template\header.php on line 1

**Comment by niiell** [comment]
u can edit code in library/config.php
